### ISSUE TITLE
Merit_Feature parsing error

### ISSUE THREAD

**Issue by holgerpieta** [holgerpieta/Toshiba-AC-mqtt#1]
Something goes wrong in merit_feature parsing.

**Comment by phoenix-anasazi** [comment]
Hi,

when I try to run toshiba_ac_to_mqtt.py I get the following error messages (I changed the configuration section accordingly):
`~/Toshiba/Toshiba-AC-mqtt $ python3 toshiba_ac_to_mqtt.py
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/lib/python3.7/contextlib.py", line 188, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/pi/.local/lib/python3.7/site-packages/asyncio_mqtt/client.py", line 330, in unfiltered_messages
    yield generator
  File "toshiba_ac_to_mqtt.py", line 150, in mqtt_ac_task
    devices = await device_manager.get_devices()
  File "/home/pi/Toshiba/Toshiba-AC-mqtt/toshiba_ac/device_manager.py", line 149, in get_devices
    self.http_api
  File "/home/pi/Toshiba/Toshiba-AC-mqtt/toshiba_ac/device.py", line 91, in __init__
    self.load_supported_merit_features(merit_feature, ac_model_id)
  File "/home/pi/Toshiba/Toshiba-AC-mqtt/toshiba_ac/device.py", line 128, in load_supported_merit_features
    floor, _, cdu_silent, pure_ion, fireplace, heating_8c, _, _ = struct.unpack('????????', bytes.fromhex('0' + '0'.join(f'{merit_byte:08b}')))
ValueError: non-hexadecimal number found in fromhex() arg at position 1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "toshiba_ac_to_mqtt.py", line 78, in cancel_tasks
    res.append( task.result() )
  File "toshiba_ac_to_mqtt.py", line 57, in log_unfiltered_message
    async for msg in messages:
  File "/home/pi/.local/lib/python3.7/site-packages/asyncio_mqtt/client.py", line 382, in _message_generator
    raise MqttError("Disconnected during message iteration")
asyncio_mqtt.error.MqttError: Disconnected during message iteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "toshiba_ac_to_mqtt.py", line 217, in <module>
    asyncio.run( main() )
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "toshiba_ac_to_mqtt.py", line 211, in main
    await mqtt_ac_task()
  File "toshiba_ac_to_mqtt.py", line 207, in mqtt_ac_task
    logger.debug( 'mqtt_ac_task finished.' )
  File "/usr/lib/python3.7/contextlib.py", line 652, in __aexit__
    raise exc_details[1]
  File "/usr/lib/python3.7/contextlib.py", line 635, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/usr/lib/python3.7/contextlib.py", line 545, in _exit_wrapper
    await callback(*args, **kwds)
  File "toshiba_ac_to_mqtt.py", line 89, in cancel_tasks
    logger.error( f'Exception occured in cancelled task {task.get_name()}')
AttributeError: '_asyncio.Task' object has no attribute 'get_name'
`

When I run python3 toshiba_ac_gui.py I get also some errors (dependancy warning), but the gui sample runs and I can control the AC. Does this help for troubleshooting?

`/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
[2022-04-10 15:38:07,173] DEBUG    toshiba_ac.utils.http_api: Sending POST to https://toshibamobileservice.azurewebsites.net/api/Consumer/Login
[2022-04-10 15:38:07,477] DEBUG    toshiba_ac.utils.http_api: Response code: 200
[2022-04-10 15:38:07,478] DEBUG    toshiba_ac.utils.http_api: Sending POST to https://toshibamobileservice.azurewebsites.net/api/Consumer/RegisterMobileDevice
[2022-04-10 15:38:07,607] DEBUG    toshiba_ac.utils.http_api: Response code: 200
[2022-04-10 15:38:07,888] DEBUG    toshiba_ac.utils.http_api: Sending GET to https://toshibamobileservice.azurewebsites.net/api/AC/GetConsumerACMapping
[2022-04-10 15:38:07,952] DEBUG    toshiba_ac.utils.http_api: Response code: 200
[2022-04-10 15:38:07,952] DEBUG    toshiba_ac.device_manager: Found devices: {Wintergarten: {MeritFeature: ac00, Model id: 2, Firmware version: 3.4.00, Initial state: 31431741314b0010157ffe0b00001001000000}
[2022-04-10 15:38:07,953] DEBUG    toshiba_ac.device: [Wintergarten] Supported AC statuses: {On, Off, None}, Supported AC modes: {None, Auto, Cool, Dry, Fan, Heat}, Supported AC fan modes: {Auto, Quiet, Low, Medium Low, Medium, Medium High, High, None}, Supported AC swing modes: {None, Off, Swing Vertical}, Supported AC power selections: {Power 50, Power 75, Power 100, None}, Supported AC merit B: {None, Off, Fireplace 1, Fireplace 2}, Supported AC merit A: {None, Off, Sleep Care, Comfort, High Power, Eco, Floor, Cdu Silent 1, Cdu Silent 2, Heating 8C}, Supported AC air pure ion: {None, Off}, Supported AC self cleaning: {On, Off, None}, Supported AC energy report: No
[2022-04-10 15:38:07,953] DEBUG    toshiba_ac.device_manager: Adding device Wintergarten
[2022-04-10 15:38:07,954] DEBUG    toshiba_ac.utils.http_api: Sending GET to https://toshibamobileservice.azurewebsites.net/api/AC/GetCurrentACState
[2022-04-10 15:38:08,007] DEBUG    toshiba_ac.utils.http_api: Response code: 200
`

What can I try or what info do you need? 
Thanks for your help, very much appreciated. My current workaround is a HA instance on a Raspi Zero, which works, but it would be great if I don't have to run this additionally.

Regards

**Comment by holgerpieta** [comment]
Thanks, that's at least pointing me to where the problem is, but I do not understand it in the moment.
I've made a new debug branch with a little bit more output: https://github.com/holgerpieta/Toshiba-AC-mqtt/tree/debug
Please check that out and run it, then post the output again.

**Comment by phoenix-anasazi** [comment]
With the debug version I only get the following output:
`~/Toshiba/debug/Toshiba-AC-mqtt $ python3 toshiba_ac_to_mqtt.py
Traceback (most recent call last):
  File "toshiba_ac_to_mqtt.py", line 29, in <module>
    from toshiba_ac.device_manager import ToshibaAcDeviceManager
  File "/home/pi/Toshiba/debug/Toshiba-AC-mqtt/toshiba_ac/device_manager.py", line 24, in <module>
    from toshiba_ac.http_api import ToshibaAcHttpApi
  File "/home/pi/Toshiba/debug/Toshiba-AC-mqtt/toshiba_ac/http_api.py", line 25, in <module>
    from toshiba_ac.device import ToshibaAcDeviceEnergyConsumption
  File "/home/pi/Toshiba/debug/Toshiba-AC-mqtt/toshiba_ac/device.py", line 130
    merit_byte_join = '0' + '0'.join(f'{merit_byte:08b}')
                  ^
SyntaxError: invalid syntax`
I add a picture so you can see, where the arrow is pointing:
![grafik](https://user-images.githubusercontent.com/63506636/162628840-865408d2-4f60-4096-bb55-6d74abc7cbff.png)

**Comment by holgerpieta** [comment]
Ah, sorry, I missed a bracket. Please pull and try again.

**Comment by phoenix-anasazi** [comment]
No problem, here the output:
`~/Toshiba/debug/Toshiba-AC-mqtt $ python3 toshiba_ac_to_mqtt.py
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
2022-04-10 18:46:24,624:DEBUG:toshiba_ac.device: merit_byte: -84
2022-04-10 18:46:24,624:DEBUG:toshiba_ac.device: merit_byte:80b: -1010100
2022-04-10 18:46:24,624:DEBUG:toshiba_ac.device: merit_byte_join: 0-01000100010000
Traceback (most recent call last):
  File "/usr/lib/python3.7/contextlib.py", line 188, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/pi/.local/lib/python3.7/site-packages/asyncio_mqtt/client.py", line 330, in unfiltered_messages
    yield generator
  File "toshiba_ac_to_mqtt.py", line 150, in mqtt_ac_task
    devices = await device_manager.get_devices()
  File "/home/pi/Toshiba/debug/Toshiba-AC-mqtt/toshiba_ac/device_manager.py", line 149, in get_devices
    self.http_api
  File "/home/pi/Toshiba/debug/Toshiba-AC-mqtt/toshiba_ac/device.py", line 91, in __init__
    self.load_supported_merit_features(merit_feature, ac_model_id)
  File "/home/pi/Toshiba/debug/Toshiba-AC-mqtt/toshiba_ac/device.py", line 132, in load_supported_merit_features
    floor, _, cdu_silent, pure_ion, fireplace, heating_8c, _, _ = struct.unpack('????????', bytes.fromhex('0' + '0'.join(f'{merit_byte:08b}')))
ValueError: non-hexadecimal number found in fromhex() arg at position 1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "toshiba_ac_to_mqtt.py", line 78, in cancel_tasks
    res.append( task.result() )
  File "toshiba_ac_to_mqtt.py", line 57, in log_unfiltered_message
    async for msg in messages:
  File "/home/pi/.local/lib/python3.7/site-packages/asyncio_mqtt/client.py", line 382, in _message_generator
    raise MqttError("Disconnected during message iteration")
asyncio_mqtt.error.MqttError: Disconnected during message iteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "toshiba_ac_to_mqtt.py", line 217, in <module>
    asyncio.run( main() )
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "toshiba_ac_to_mqtt.py", line 211, in main
    await mqtt_ac_task()
  File "toshiba_ac_to_mqtt.py", line 207, in mqtt_ac_task
    logger.debug( 'mqtt_ac_task finished.' )
  File "/usr/lib/python3.7/contextlib.py", line 652, in __aexit__
    raise exc_details[1]
  File "/usr/lib/python3.7/contextlib.py", line 635, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/usr/lib/python3.7/contextlib.py", line 545, in _exit_wrapper
    await callback(*args, **kwds)
  File "toshiba_ac_to_mqtt.py", line 89, in cancel_tasks
    logger.error( f'Exception occured in cancelled task {task.get_name()}')
AttributeError: '_asyncio.Task' object has no attribute 'get_name'
`

**Comment by holgerpieta** [comment]
Thanks, I think I found the problem. Please try again.

Also that part of the library was significantly changed upstream, so we probably should not spend too much time fixing the old version. But if the change helps, that would still be nice.

**Comment by phoenix-anasazi** [comment]
Thanks, unfortunately there still are errors.
`~/Toshiba/debug/Toshiba-AC-mqtt $ python3 toshiba_ac_to_mqtt.py
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
2022-04-10 19:02:13,126:DEBUG:toshiba_ac.device: merit_string: ac
2022-04-10 19:02:13,126:DEBUG:toshiba_ac.device: merit_byte: 172
2022-04-10 19:02:13,126:DEBUG:toshiba_ac.device: merit_byte:80b: 10101100
2022-04-10 19:02:13,127:DEBUG:toshiba_ac.device: merit_byte_join: 0100010001010000
2022-04-10 19:02:13,127:DEBUG:toshiba_ac.device: [Wintergarten] Supported merit A features: Off, High Power, Eco, Floor, Cdu Silent 1, Cdu Silent 2, Heating 8C. Supported merit B features: Off, Fireplace 1, Fireplace 2. Pure ION supported: False
ValueError: 0 is not a valid AcScheduler
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.7/contextlib.py", line 188, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/pi/.local/lib/python3.7/site-packages/asyncio_mqtt/client.py", line 330, in unfiltered_messages
    yield generator
  File "toshiba_ac_to_mqtt.py", line 150, in mqtt_ac_task
    devices = await device_manager.get_devices()
  File "/home/pi/Toshiba/debug/Toshiba-AC-mqtt/toshiba_ac/device_manager.py", line 158, in get_devices
    await asyncio.gather(*connects)
  File "/home/pi/Toshiba/debug/Toshiba-AC-mqtt/toshiba_ac/device.py", line 98, in connect
    self.fcu_state = ToshibaAcFcuState.from_hex_state( self.initial_ac_state )
  File "/home/pi/Toshiba/debug/Toshiba-AC-mqtt/toshiba_ac/fcu_state.py", line 181, in from_hex_state
    state.decode(hex_state)
  File "/home/pi/Toshiba/debug/Toshiba-AC-mqtt/toshiba_ac/fcu_state.py", line 266, in decode
    self.ac_utc_minutes) = data
  File "/home/pi/Toshiba/debug/Toshiba-AC-mqtt/toshiba_ac/fcu_state.py", line 442, in ac_scheduler
    self._ac_scheduler = ToshibaAcFcuState.AcScheduler(val)
  File "/usr/lib/python3.7/enum.py", line 310, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.7/enum.py", line 564, in __new__
    raise exc
  File "/usr/lib/python3.7/enum.py", line 548, in __new__
    result = cls._missing_(value)
  File "/usr/lib/python3.7/enum.py", line 577, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 0 is not a valid AcScheduler
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "toshiba_ac_to_mqtt.py", line 78, in cancel_tasks
    res.append( task.result() )
  File "toshiba_ac_to_mqtt.py", line 57, in log_unfiltered_message
    async for msg in messages:
  File "/home/pi/.local/lib/python3.7/site-packages/asyncio_mqtt/client.py", line 382, in _message_generator
    raise MqttError("Disconnected during message iteration")
asyncio_mqtt.error.MqttError: Disconnected during message iteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "toshiba_ac_to_mqtt.py", line 217, in <module>
    asyncio.run( main() )
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "toshiba_ac_to_mqtt.py", line 211, in main
    await mqtt_ac_task()
  File "toshiba_ac_to_mqtt.py", line 207, in mqtt_ac_task
    logger.debug( 'mqtt_ac_task finished.' )
  File "/usr/lib/python3.7/contextlib.py", line 652, in __aexit__
    raise exc_details[1]
  File "/usr/lib/python3.7/contextlib.py", line 635, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/usr/lib/python3.7/contextlib.py", line 545, in _exit_wrapper
    await callback(*args, **kwds)
  File "toshiba_ac_to_mqtt.py", line 89, in cancel_tasks
    logger.error( f'Exception occured in cancelled task {task.get_name()}')
AttributeError: '_asyncio.Task' object has no attribute 'get_name'
`

**Comment by phoenix-anasazi** [comment]
If you don't want to spend more time on this it is ok for me. As I said I have a working solution, it would just be nice to get rid of the additional Raspi Zero/HA instance.

**Comment by holgerpieta** [comment]
Don't worry, we gonna dig into that some more.
We already solved the original problem and found a new one.
Please try again.

**Comment by phoenix-anasazi** [comment]
Nice, now it works! Thank you very much.
`~/Toshiba/debug/Toshiba-AC-mqtt $ python3 toshiba_ac_to_mqtt.py
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
2022-04-10 19:17:29,684:DEBUG:toshiba_ac.device: merit_string: ac
2022-04-10 19:17:29,685:DEBUG:toshiba_ac.device: merit_byte: 172
2022-04-10 19:17:29,685:DEBUG:toshiba_ac.device: merit_byte:80b: 10101100
2022-04-10 19:17:29,686:DEBUG:toshiba_ac.device: merit_byte_join: 0100010001010000
2022-04-10 19:17:29,686:DEBUG:toshiba_ac.device: [Wintergarten] Supported merit A features: Off, High Power, Eco, Floor, Cdu Silent 1, Cdu Silent 2, Heating 8C. Supported merit B features: Off, Fireplace 1, Fireplace 2. Pure ION supported: False
2022-04-10 19:17:29,740:INFO:toshiba_ac.device: [Wintergarten] Current state: Status: OFF, Mode: FAN, Temperature: 23, FanMode: AUTO, SwingMode: NOT_USED, PowerSelection: POWER_75, MeritBFeature: OFF, MeritAFeature: OFF, AirPureIon: OFF, IndoorTemperature: 22, OutdoorTemperature: UNKNOWN, Error: OK, Timer: TIMER6, RelativeHours: 0, RelativeMinutes: 0, SelfCleaning: OFF, LED: ON, Scheduler: UNKNOWN, UtcHours: 0, UtcMinutes: 0, IndoorHeatExchangerTemperature: NONE, IndoorPipeTemperature: NONE, IndoorFanRPM: NONE, CompressorOutletTemperature: NONE, CompressorInletTemperature: NONE, OutdoorHeatExchangerTemperature: NONE, CompressorFrequency: NONE, OutdoorFarnRPM: NONE, ValvePwmDutyCycle: NONE, IAC: NONE
2022-04-10 19:17:29,740:DEBUG:toshiba_ac.device: State reload sleeping for 303 seconds.
2022-04-10 19:17:29,742:INFO:toshiba_ac.device: [Wintergarten] Current state: Status: OFF, Mode: FAN, Temperature: 23, FanMode: AUTO, SwingMode: NOT_USED, PowerSelection: POWER_75, MeritBFeature: OFF, MeritAFeature: OFF, AirPureIon: OFF, IndoorTemperature: 22, OutdoorTemperature: UNKNOWN, Error: OK, Timer: TIMER6, RelativeHours: 0, RelativeMinutes: 0, SelfCleaning: OFF, LED: ON, Scheduler: UNKNOWN, UtcHours: 0, UtcMinutes: 0, IndoorHeatExchangerTemperature: NONE, IndoorPipeTemperature: NONE, IndoorFanRPM: NONE, CompressorOutletTemperature: NONE, CompressorInletTemperature: NONE, OutdoorHeatExchangerTemperature: NONE, CompressorFrequency: NONE, OutdoorFarnRPM: NONE, ValvePwmDutyCycle: NONE, IAC: NONE
2022-04-10 19:20:24,915:DEBUG:toshiba_ac.device: [Wintergarten] AC state from AMQP: 31451741314b0010167ffe0b00001001000000
2022-04-10 19:20:25,151:DEBUG:toshiba_ac.device: [Wintergarten] AC state from AMQP: 31451741314b0010167ffe0b00001001000000
2022-04-10 19:21:31,465:DEBUG:toshiba_ac.device: [Wintergarten] AC state from AMQP: ff451441ffff00ffffffffffffffffffffffff
2022-04-10 19:21:31,466:INFO:toshiba_ac.fcu_state: Wintergarten: Setpoint temperature changed from 23 to 20
2022-04-10 19:21:31,466:INFO:toshiba_ac.device: [Wintergarten] Current state: Status: OFF, Mode: FAN, Temperature: 20, FanMode: AUTO, SwingMode: NOT_USED, PowerSelection: POWER_75, MeritBFeature: OFF, MeritAFeature: OFF, AirPureIon: OFF, IndoorTemperature: 22, OutdoorTemperature: UNKNOWN, Error: OK, Timer: TIMER6, RelativeHours: 0, RelativeMinutes: 0, SelfCleaning: OFF, LED: ON, Scheduler: UNKNOWN, UtcHours: 0, UtcMinutes: 0, IndoorHeatExchangerTemperature: NONE, IndoorPipeTemperature: NONE, IndoorFanRPM: NONE, CompressorOutletTemperature: NONE, CompressorInletTemperature: NONE, OutdoorHeatExchangerTemperature: NONE, CompressorFrequency: NONE, OutdoorFarnRPM: NONE, ValvePwmDutyCycle: NONE, IAC: NONE`

On the MQTT-Brokerside I get the following readings:
`READINGS:
     2022-04-10 15:34:55   IODev           [MQTTserv](http://192.168.2.245:8083/fhem?detail=MQTTserv)
     2022-04-10 19:22:02   status          offline
     2022-04-10 19:21:31   status_Name     Wintergarten
     2022-04-10 19:17:29   status_Status_ac_air_pure_ion 16
     2022-04-10 19:17:29   status_Status_ac_error 254
     2022-04-10 19:17:29   status_Status_ac_fan_mode 65
     2022-04-10 19:17:29   status_Status_ac_indoor_temperature 22
     2022-04-10 19:17:29   status_Status_ac_led 1
     2022-04-10 19:17:29   status_Status_ac_merit_a_feature 0
     2022-04-10 19:17:29   status_Status_ac_merit_b_feature 0
     2022-04-10 19:17:29   status_Status_ac_mode 69
     2022-04-10 19:17:29   status_Status_ac_power_selection 75
     2022-04-10 19:17:29   status_Status_ac_relative_hours 0
     2022-04-10 19:17:29   status_Status_ac_relative_minutes 0
     2022-04-10 19:17:29   status_Status_ac_self_cleaning 16
     2022-04-10 19:17:29   status_Status_ac_status 49
     2022-04-10 19:17:29   status_Status_ac_swing_mode 49
     2022-04-10 19:21:31   status_Status_ac_temperature 20
     2022-04-10 19:17:29   status_Status_ac_timer_mode 11
     2022-04-10 19:17:29   status_Status_ac_utc_hours 0
     2022-04-10 19:17:29   status_Status_ac_utc_minutes 0`
Couldn't publish to the ac for now. Have to try a few things. Is there a "translation" between these numbers and the modes? Otherwise I am just testing through...

**Comment by holgerpieta** [comment]
Nice. I've merged the changes into main, so you can switch back to it, if you want to. Also reduced the debug output again.

Then I noticed that the readme was wrong: The bridge subscribes to ac/.../cmd and not to ac/.../status.

You can find the mapping (or translation) in `toshiba_ac/fcu_state.py` lines 36 to 160. Please be aware that the numbers are hexadecimal on the AC side, but decimal on MQTT / node-red side. So you have to convert that.
BUT: You can actually send commands as strings, you do not need to use numbers.

So, say you want to set the fan to HIGH, which is hexadecimal 36 or decimal 54.

Topic: ac/Wintergarten/cmd
Payload: {"ac_fan_mode": "HIGH"}

This is the same as
Payload: {"ac_fan_mode": 54}

Make sure that you have "" around the strings, but none around the numbers.

If you send something the bridge doesn't understand, it will crash.
That is not good and I will try to fix it in the next days. In the moment just be careful what you send.

I guess you are German, because you AC is called "Wintergarten". If you run into a language barrier, you may write in German. But if English is fine for you, let's leave it like that such that other people can hopefully benefit from the discussion, too.

**Comment by phoenix-anasazi** [comment]
Thank you very much again. Yes, I am german but english is ok. I will try sending messages tomorrow and give you feedback.

**Comment by phoenix-anasazi** [comment]
Works like a charm. Thank you very much! Now I can control my AC with FHEM.

**Comment by holgerpieta** [comment]
Nice.
You solved that systemd problem?

**Comment by phoenix-anasazi** [comment]
Yes, I hope you didn't get a notification for each edit I made ;-)
I had to install the python packages (asyncio, etc) also for root user. It still runs into a timeout at the first start , but when it restarts it stays active. So this is fine for me.

**Comment by holgerpieta** [comment]
Don't worry, I only got one notification. Only when I logged in to answer I found everything gone. :)

Anyway, please do not run the bridge as a system level service (i.e. as root). If there is something wrong with it, it could compromise the whole system.
If you put the service file in `~/.config/systemd/user/` you can use it like any other service, just that instead of `sudo systemctl [rest of command]` you use `systemctl --user [rest of command]` (without the sudo). Everything else stays basically the same. (Also use `journalctl --user-unit=[name of the unit]` to get the logs.)
This will run the service (and therefore the bridge) as the logged in user, i.e. `pi` I guess.

And you might want to read up on Python's virtual environments (venv), which allow you to install packages specifically for a project instead of messing up your global install. But I do not know how to use them in a service. Maybe you need to write a wrapper shell script.

**Comment by phoenix-anasazi** [comment]
Thanks for your hint. I will change it to run as user. I tried the venv install but had some problems at first and therefor used the global install. But as I know it works now I can try to use it in a venv. I am sure there is an instruction on the internet on how to use venv in a service ;-)

**Comment by phoenix-anasazi** [comment]
Thank you very much again for your help. Runs perfectly. I have installed the bridge in a virtual env and changed my service-file to run it as user. If I would put it in the user directory as you suggested, the user has to be logged in. At least thats how it is described in the ubuntuusers.de-Wiki. In case someone else needs the config, here it is:
`[Unit]
Description=autostart-toshiba-ac.service
Wants=network.target
After=network-online.target
StartLimitIntervalSec=20m
StartLimitBurst=3
[Service]
User=1000
Environment="PATH=/path/to/env/bin/python3"
ExecStart=/path/to/env/bin/python3 /path/to/py/Toshiba-AC-mqtt/toshiba_ac_to_mqtt.py
Restart=always
RestartSec=120
TimeoutStopSec=70
[Install]
WantedBy=multi-user.target default.target`

**Comment by holgerpieta** [comment]
There are some buttons to press to make it work, but then you can also auto-start systemd user services at boot. I can confirm that it works, my smart-home raspi functions that way:
https://wiki.archlinux.org/title/systemd/User#Automatic_start-up_of_systemd_user_instances (don't forget to add sudo before the command).
Or in German:
https://wiki.ubuntuusers.de/systemd/User_Units/#User-Units-ohne-Anmeldung-starten

**Comment by phoenix-anasazi** [comment]
*facepalm* I should have read the article I linked to the end... Thanks, now it is running in venv and called by a user service. Really cool.
Is there a possibility to send you some coffee money for your work?

**Comment by holgerpieta** [comment]
Thanks for the generous offer, but in the moment I'm just happy that there is at least one other people benefiting from my work. And that all the effort wasn't just for me alone.

**Comment by holgerpieta** [comment]
Fixed in 05314addf808b081a8d250609d5818013deeca13 and ff97dc8bf58cfdc9fe302e683ec18d3ad3fc741f.
Issue closed.

Please continue discussing here if there are any issues left. Or open a new issue, if there is another problem.
