### ISSUE TITLE
Issue getting it to run Something failed while connecting: mobileapi.toshibahomeaccontrols.com/api/Consumer/Login

### ISSUE THREAD

**Issue by bartdesign** [holgerpieta/Toshiba-AC-mqtt#2]
Hi, First of all thank you for making this. I was looking for something to bypass homeassistant ;-) 
I'm trying to run this on ubuntu. But it's giving me a weird error: 

2022-12-02 23:35:48,775:WARNING:mqtt: unfiltered_messages() is deprecated and will be removed in a future version. Use messages() instead.
2022-12-02 23:35:48,776:ERROR:toshiba_ac.device_manager: Something failed while connecting: mobileapi.toshibahomeaccontrols.com/api/Consumer/Login
Traceback (most recent call last):
  File "/home/bart/Toshiba-AC-mqtt/toshiba_ac/device_manager.py", line 52, in connect
    await self.http_api.connect()
  File "/home/bart/Toshiba-AC-mqtt/toshiba_ac/http_api.py", line 104, in connect
    res = await self.request_api(self.LOGIN_PATH, post=post, headers=headers)
  File "/home/bart/Toshiba-AC-mqtt/toshiba_ac/http_api.py", line 85, in request_api
    async with method() as response:
  File "/home/bart/.local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/bart/.local/lib/python3.8/site-packages/aiohttp/client.py", line 508, in _request
    req = self._request_class(
  File "/home/bart/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/home/bart/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 364, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: mobileapi.toshibahomeaccontrols.com/api/Consumer/Login
2022-12-02 23:35:48,779:WARNING:toshiba_ac.device_manager: Shutting down

I have triple checked my username and password; also i have tried to do the HTTP call with postman and this works correctly with my credentials. I cannot figure out why this doesn't want to connect. I've tried this on two seperate machines. Any ideas? :-)

**Comment by bartdesign** [comment]
So i already found the fix. I needed to put https:// infront of the Base_URL. But now i crashes again with another error: 

`2022-12-02 23:47:52,895:WARNING:mqtt: unfiltered_messages() is deprecated and will be removed in a future version. Use messages() instead.
2022-12-02 23:47:53,752:ERROR:__main__: Exception occured in cancelled task Task-4
2022-12-02 23:47:53,752:ERROR:__main__: Disconnected during message iteration
Traceback (most recent call last):
  File "/usr/lib/python3.8/contextlib.py", line 189, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/bart/.local/lib/python3.8/site-packages/asyncio_mqtt/client.py", line 516, in unfiltered_messages
    yield generator
  File "toshiba_ac_to_mqtt.py", line 150, in mqtt_ac_task
    devices = await device_manager.get_devices()
  File "/home/bart/Toshiba-AC-mqtt/toshiba_ac/device_manager.py", line 158, in get_devices
    await asyncio.gather(*connects)
  File "/home/bart/Toshiba-AC-mqtt/toshiba_ac/device.py", line 98, in connect
    self.fcu_state = ToshibaAcFcuState.from_hex_state( self.initial_ac_state )
  File "/home/bart/Toshiba-AC-mqtt/toshiba_ac/fcu_state.py", line 182, in from_hex_state
    state.decode(hex_state)
  File "/home/bart/Toshiba-AC-mqtt/toshiba_ac/fcu_state.py", line 254, in decode
    self.ac_merit_b_feature,
  File "/home/bart/Toshiba-AC-mqtt/toshiba_ac/fcu_state.py", line 366, in ac_merit_b_feature
    self._ac_merit_b_feature = ToshibaAcFcuState.AcMeritBFeature(val)
  File "/usr/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.8/enum.py", line 663, in __new__
    raise ve_exc
ValueError: 1 is not a valid AcMeritBFeature

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "toshiba_ac_to_mqtt.py", line 78, in cancel_tasks
    res.append( task.result() )
  File "toshiba_ac_to_mqtt.py", line 57, in log_unfiltered_message
    async for msg in messages:
  File "/home/bart/.local/lib/python3.8/site-packages/asyncio_mqtt/client.py", line 586, in _message_generator
    raise MqttError("Disconnected during message iteration")
asyncio_mqtt.error.MqttError: Disconnected during message iteration
Traceback (most recent call last):
  File "toshiba_ac_to_mqtt.py", line 217, in <module>
    asyncio.run( main() )
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "toshiba_ac_to_mqtt.py", line 211, in main
    await mqtt_ac_task()
  File "toshiba_ac_to_mqtt.py", line 150, in mqtt_ac_task
    devices = await device_manager.get_devices()
  File "/home/bart/Toshiba-AC-mqtt/toshiba_ac/device_manager.py", line 158, in get_devices
    await asyncio.gather(*connects)
  File "/home/bart/Toshiba-AC-mqtt/toshiba_ac/device.py", line 98, in connect
    self.fcu_state = ToshibaAcFcuState.from_hex_state( self.initial_ac_state )
  File "/home/bart/Toshiba-AC-mqtt/toshiba_ac/fcu_state.py", line 182, in from_hex_state
    state.decode(hex_state)
  File "/home/bart/Toshiba-AC-mqtt/toshiba_ac/fcu_state.py", line 254, in decode
    self.ac_merit_b_feature,
  File "/home/bart/Toshiba-AC-mqtt/toshiba_ac/fcu_state.py", line 366, in ac_merit_b_feature
    self._ac_merit_b_feature = ToshibaAcFcuState.AcMeritBFeature(val)
  File "/usr/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.8/enum.py", line 663, in __new__
    raise ve_exc
ValueError: 1 is not a valid AcMeritBFeature`

**Comment by bartdesign** [comment]
Ok, i've got it working. I had to add a extra enum to AcMeritBFeature(enum):

` 
class AcMeritBFeature(Enum):
        FIREPLACE_1 = 0x02
        FIREPLACE_2 = 0x03
        OFF1 = 0x01
        OFF = 0x00
        NONE = _NONE_VAL
`
I don't know if this is the correct way to go. But it is running now! :-D

**Comment by holgerpieta** [comment]
Hey, nice that there are people who are using my stuff.
And good to hear that you've already figured it out yourself.
Now that I read your comment, I remember that I had to fix that, too, a couple of weeks ago, but I forgot to push that change.
I've pushed it now. Work on my side, maybe you can give it a try.

**Comment by bartdesign** [comment]
Thx It helps. But its stil crashing on the MeritB thing. I fixed it by adding 0x01 to the MeritB enum. Also the MQTT messages i received had numbers as status instead of the enum string value. 

So i changed the ToJson method in FCU file. In the else clause i changed it to res[name[1:]] = val.name to get this to work properly.

**Comment by holgerpieta** [comment]
Weird, it's already in the new version: https://github.com/holgerpieta/Toshiba-AC-mqtt/blob/88107117e8066a13d2d4e90206272ef3d669697b/toshiba_ac/fcu_state.py#L83
Can you show me what you changed?

The MQTT status returns numbers instead of strings because that was easier for me to parse in the receiver (i.e. Node-Red). I had planned to publish the strings as well, but never got to it (because I didn't need it).
If you like, maybe make a pull request with the old ToJson method and a new ToJsonString method and then publish the former on the old topic (i.e. ac/room/status) and the latter on a new topic (e.g. /ac/room/text_status or whatever you like).

**Comment by bartdesign** [comment]
I had some time and updated the Git. The MeritB is fixed. Thx.  I will see if i have some time the next weeks to do a pull.

**Comment by holgerpieta** [comment]
Thanks. I haven't found the time to dig into it, so I'll await your changes.
